

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.yzb.test.spring.entity
  configuration:
    map-underscore-to-camel-case: true
    use-actual-param-name: true

#通用tkmapper配置
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true
  style: camelhump
#  identity: SELECT REPLACE(UUID(),''-'','''')
#  order: BEFORE

server:
  port: 8081

